services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    expose:
     - "9000"
    depends_on:
      - back-end
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4
    expose:
      - "5252"
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: task4-proxy
    ports:
     - "80:80"
    depends_on:
      - front-end
      - back-end
